package com.qa.portfolio;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Before;
import org.junit.Test;

/**
 * Test file for EndsWith Class.
 * 
 * Run this file to assess progress.
 * 
 * DO NOT EDIT THIS FILE!
 * 
 */
public class EndsWithTest {

	private EndsWith answers;

	@Before
	public void setup() {
		answers = new EndsWith();
	}

	@Test
	public void endsWithJavaTest() {
		assertTrue(answers.endsJava("ilovejava"));
	}
	
	@Test
	public void endsWithJavaIgnoreCaseTest() {
		assertTrue(answers.endsJava("iloveJaVa"));		
	}
	
	@Test
	public void containsJavaButDoesNotEndWithJava() {
		assertFalse(answers.endsJava("ilovejavamoreeveryday"));		
	}
	
	@Test
	public void doesNotContainJava() {
		assertFalse(answers.endsJava("python_is_cool"));
	}

	
}
